"""Generate 01_Company_Context.md from YAML input files (reverse of loader).

The markdown is a human-readable view; YAML is the canonical source.
"""
from __future__ import annotations

from pathlib import Path


def generate_context_md(case_path: str | Path, output_path: str | Path | None = None) -> Path:
    """Render input/*.yaml as 01_Company_Context.md (human-readable view)."""
    case_path = Path(case_path)
    input_root = case_path / "input"

    if output_path is None:
        output_path = case_path / "context" / "01_Company_Context.md"
    output_path = Path(output_path)

    classification = _read(input_root / "company" / "classification.yaml")
    goals = _read(input_root / "company" / "business_goals.yaml")
    stakeholders = _read(input_root / "company" / "stakeholders.yaml")
    systems = _read(input_root / "architecture" / "systems.yaml")
    stores = _read(input_root / "architecture" / "data_stores.yaml")
    flows = _read(input_root / "architecture" / "data_flows.yaml")

    md = f"""---
document_id: AEGIS-COMMON-01
title: AEGIS Intake Form — Company Context Assessment (AUTO-GENERATED)
version: 3.0
author: AEGIS Pipeline (auto-generated from YAML input)
status: AUTO-GENERATED
case_study: {case_path.name}
---

# AEGIS Intake Form — Company Context Assessment

> **AUTO-GENERATED** from `input/*.yaml`. Edit the YAML files; re-run the generator.

## 2. Company Profile

```yaml
{classification}
```

## 3. Business Goals

```yaml
{goals}
```

## 4. Stakeholders

```yaml
{stakeholders}
```

## 5. Architecture

### 5.1 Systems

```yaml
{systems}
```

### 5.2 Data Stores

```yaml
{stores}
```

### 5.3 Data Flows

```yaml
{flows}
```

---
_Generated by `generate_context_md()` from `input/*.yaml`_
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md)
    return output_path


def _read(path: Path) -> str:
    if not path.exists():
        return "(file not present)"
    return path.read_text()